require("config.default_config")
bag_path="../bags/2020-03-05-17-51-12-GDC1-south.bag"
lidar_topic="/Cobot/Laser"
odom_topic="/Cobot/Odometry"
auto_lc=true
pose_number=300
differential_odom=true
rotation_weight=2
translation_weight=3
