require("config.default_config")
bag_path="../bags/2020-03-09-19-02-17-GDC3-long-rewritten.bag"
lidar_topic="/Cobot/Laser"
odom_topic="/Cobot/Odometry"
auto_lc=true
pose_number=1000
differential_odom=false
rotation_weight=2
translation_weight=3
max_lidar_range=8.5