require("config.default_config")
bag_path="data/2020-03-05-17-51-12-GDC1-south.bag"
lidar_topic="/Cobot/Laser"
odom_topic="/Cobot/Odometry"
auto_lc=false
pose_number=1000
differential_odom=true
rotation_weight=2
translation_weight=2